In [1]:
!pip install -q tabula-py

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 75.4 MB/s eta 0:00:00

In [2]:
import tabula
import pandas as pd
import string

In [3]:
master=tabula.read_pdf("/content/beececurriculum.pdf", stream=True,pages='all')

WARNING:tabula.io:Got stderr: Jan 07, 2023 1:50:37 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Jan 07, 2023 1:50:37 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Jan 07, 2023 1:50:37 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 17 fonts
Jan 07, 2023 1:50:44 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Jan 07, 2023 1:50:44 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Jan 07, 2023 1:50:45 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Jan 07, 2023 1:50:45 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Jan 07, 2023 1:51:00 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored
Jan 07, 2023 1:51:00 PM org.apache.fontbox.ttf.CmapSubtable processSubtype14
WARNING: Format 14 cmap table is not supported and will be ignored

,Unnamed: 0,Unnamed: 1,Unnamed: 2,SEMESTER 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Sl.,Course,Course,NaN,NaN,NaN,NaN,NaN,Marks Page
1,NaN,NaN,NaN,Course Title L,NaN,T,P,C,NaN
2,No.,Type,Code,NaN,NaN,NaN,NaN,NaN,No. CAE ESE
3,1,Theory,SMTA1101,Engineering Mathematics – I 3,NaN,*,0,3,50 50 1
4,2,Theory,SPHA1101,Physics for Engineers 3,NaN,1,0,4,50 50 2
5,3,Theory,SEEA1101,Electrical Technology 3,NaN,*,0,3,50 50 4
6,4,Theory,SCSA1202,Programming in C and C++ 3,NaN,0,0,3,50 50 5
7,5,Theory,SECA1101,Electronic Devices 3,NaN,0,0,3,50 50 6
8,6,Theory,SMEA1102,Engineering Drawing 1,NaN,0,4,3,50 50 7
9,7,Practical,SPHA2101,Physics Lab 0,NaN,0,2,1,25 25 8
10,8,Practical,SEEA2101,Electrical Engineering Lab 0,NaN,0,4,2,50 50 9
11,9,Practical,SECA2101,Electronic Devices Lab 0,NaN,0,4,2,50 50 10
12,NaN,NaN,NaN,Total Credits for Semester 1 – 24,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,Total Marks for Semester 1 - 850,NaN,NaN,NaN,NaN,NaN

In [17]:
refined=[]
for num in range(7):
  temp=master[num].drop(['Unnamed: 0','Unnamed: 1', 'Unnamed: 3','Unnamed: 4', 'Unnamed: 5', 'Unnamed: 7'], axis=1)
  if 'Unnamed: 8' in temp.columns:
    temp.drop(['Unnamed: 8'], inplace=True, axis=1)

  if(pd.isna(temp.iloc[3:4, -1]).bool()):
    temp.drop([0,1,2,3], axis=0, inplace=True)
  else:
    temp.drop([0,1,2], axis=0, inplace=True) 

  temp.columns=['Subject_Code','Subject','Credits']
  temp.dropna(axis=0, how="all", inplace=True)
  temp.reset_index(drop=True, inplace=True)  
  refined.append(temp[:-2])

len(refined)

7

**INDIVIDUAL CLEANING:**

In [18]:
final=[]

In [20]:
def nstrip(num):
  for val in range(len(refined[num])):
    refined[num]["Subject"][val]=refined[num]["Subject"][val].rstrip('0123456789')

SEM 1:

In [19]:
refined[0]

  Subject_Code                        Subject Credits
0     SMTA1101  Engineering Mathematics – I 3       3
1     SPHA1101        Physics for Engineers 3       4
2     SEEA1101        Electrical Technology 3       3
3     SCSA1202     Programming in C and C++ 3       3
4     SECA1101           Electronic Devices 3       3
5     SMEA1102          Engineering Drawing 1       3
6     SPHA2101                  Physics Lab 0       1
7     SEEA2101   Electrical Engineering Lab 0       2
8     SECA2101       Electronic Devices Lab 0       2

In [21]:
nstrip(0)
final.append(refined[0])

SEM 2:

In [23]:
refined[1]

,Subject_Code,Subject,Credits
0,SHSA1101,Technical English 3,3
1,SMTA1201,Engineering Mathematics – II 3,3
2,SCYA1101,Engineering Chemistry 3,4
3,SCSA1103,Data structures 3,3
4,NaN,Environmental Science and,NaN
5,SBTA1101,2,-
6,NaN,Engineering,NaN
7,SECA1201,Digital Logic Circuits 3,3
8,SCYA 2101 Engineering Chemistry Lab,0,1
9,NaN,Programming in C & Data Structures,NaN
10,SCSA2202,0,2
11,NaN,Lab,NaN

In [24]:
nstrip(1)

In [27]:
refined[1]["Subject_Code"][4]="SBTA1101"
refined[1]["Subject"][4]="Environmental Science and Engineering"
refined[1]["Subject_Code"][8]="SCYA2101"
refined[1]["Subject"][8]="Engineering Chemistry Lab"
refined[1]["Subject_Code"][9]="SCSA2202"
refined[1]["Credits"][9]="3"

final.append(refined[1].drop([5,6,10,11], axis=0).reset_index(drop=True))

SEM 3:

In [32]:
refined[2]

  Subject_Code                          Subject Credits
0     SMTA1301    Engineering Mathematics - III       3
1          NaN  Electrical Circuits and Network     NaN
2     SEEA1304                              NaN       3
3          NaN                         Analysis     NaN
4     SECA1301              Signals and Systems       3
5     SECA1302          Electronic Circuits - I       3
6     SEEA1302           Electromagnetic Theory       3
7     SECA1303            Analog  Communication       3
8     SECA2301       Circuits  and Networks Lab       2
9     SECA2302      Electronic Circuits - I Lab       2

In [33]:
refined[2]["Subject_Code"][1]="SEE1304"
refined[2]["Credits"][1]="3"

final.append(refined[2].drop([2,3], axis=0).reset_index(drop=True))

SEM 4:

In [35]:
refined[3]

  Subject_Code                          Subject Credits
0     SMTA1401  Engineering Mathematics -  IV 3       3
1     SECA1401       Electronic Circuits - II 3       3
2          NaN      Transmission Lines and Wave     NaN
3     SECA1402                                3       3
4          NaN                           guides     NaN
5     SECA1403         Digital  Communication 3       3
6          NaN                   Elective – I 3       3
7     SAIC4001                   Industry 4.0 2       2
8     SECA2401   Electronic Circuits - II Lab 0       2
9     SECA2402  Communication Engineering Lab 0       2

In [36]:
nstrip(3)

In [38]:
refined[3]['Subject_Code'][2]='SECA1402'
refined[3]['Credits'][2]='3'

final.append(refined[3].drop([3,4],axis=0).reset_index(drop=True))

SEM 5:

In [40]:
refined[4]

  Subject_Code                           Subject Credits
0     SECA1501       Digital Signal Processing 3       3
1     SECA1502      Analog Integrated Circuits 3       3
2     SECA1503                CMOS VLSI Design 3       3
3     SECA1504   Antennas and Wave Propagation 3       3
4          NaN                   Elective – II 3       3
5     SEEA1502                 Control Systems 3       3
6     SECA2501   Digital Signal Processing Lab 0       2
7     SECA2502  Analog Integrated Circuits Lab 0       2
8      S13APT1           Professional Training 0       2

In [41]:
nstrip(4)

In [43]:

final.append(refined[4].drop([3], axis=0).reset_index(drop=True))

SEM 6:

In [45]:
refined[5]

  Subject_Code                                   Subject Credits
0     SECA1601    Microprocessors and Microcontrollers 3       3
1     SECA1602                      Programming in HDL 3       3
2     SECA1603                        Embedded Systems 3       3
3     SECA1604                       Computer Networks 3       3
4          NaN                          Elective – III 3       3
5     SECA2601  Microprocessor and Microcontroller Lab 0       2
6     SECA2602                        VLSI  Design Lab 0       2
7   S13AIPROJ1              Interdisciplinary  Project 0       3

In [46]:
nstrip(5)

In [49]:
final.append(refined[5])

SEM 7:

In [51]:
refined[6]

  Subject_Code                      Subject Credits
0     SECA1701                            3       3
1          NaN                Communication     NaN
2     SECA1702     Wireless Communication 3       3
3     SECA1703         Internet of Things 3       3
4          NaN              Elective – IV 3       3
5          NaN              Elective - V  3       3
6     SECA2701  Microwave and Optical Lab 0       2
7    S13APROJ1   Project Work (Phase - I) 0       3

In [56]:
nstrip(6)
refined[6]["Subject"][0]="Microwave and Optical Communication"

<ipython-input-56-8e842e6c0f66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refined[6]["Subject"][0]="Microwave and Optical Communication"

In [59]:
final.append(refined[6].drop([1], axis=0).reset_index(drop=True))

SEM 8:

In [61]:
master[7]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,SEMESTER 8,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marks,NaN
1,NaN,Course,Course,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Page
2,Sl. No.,NaN,NaN,NaN,Course Title,L,NaN,T,P,C,NaN,NaN
3,NaN,Type,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No.
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAE ESE,NaN
5,NaN,NaN,NaN,Principles,of Management and,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,Theory,SBAA4002,NaN,NaN,3,NaN,0,0,3,50 50,58
7,NaN,NaN,NaN,Professional Ethics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2,Theory,NaN,Elective - VI,NaN,3,NaN,0,0,3,50 50,NaN
9,3,Project,S13APROJ2,Project Work (Phase - II),NaN,0,NaN,0,14,7,50 50,NaN
10,NaN,NaN,NaN,Total Credits for Semester 8 - 13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,Total Marks for Semester 8 - 300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
temp=master[7].drop(["Unnamed: 0","Unnamed: 1","SEMESTER 8","Unnamed: 4","Unnamed: 5","Unnamed: 6","Unnamed: 7","Unnamed: 9","Unnamed: 10"], axis=1)
temp.drop([0,1,2,3,4,5,7,10,11], axis=0, inplace=True)
temp.columns=['Subject_Code','Subject','Credits']
temp["Subject"][6]="Principles of Management and Professional Ethics"
final.append(temp.reset_index(drop=True))

In [64]:
len(final)

8

In [65]:
import os
os.chdir("/content/ECE")

**CSV:**

In [66]:
names=["sem1","sem2","sem3","sem4","sem5","sem6","sem7","sem8"]
for df,name in zip(final, names): 
   df.to_csv(name + '.csv')